### PR TITLE
Added classes version to the file name

### PR DESCRIPTION
**Pull request by Mmiglio**
Renamed test file to include class version, as requested in this comment https://github.com/cms-data/DataFormats-L1Scouting/pull/1#discussion_r1459282960

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
+daq

**Comment by smuzaffar** [comment]
+externals

is there cmssw PR which uses this new (renamed) file?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
