### PR TITLE
Added tests for BMTF stubs data source

### PR DESCRIPTION
**Pull request by Mmiglio**
Produced a new test file to include tests for the data format introduced in this PR: https://github.com/cms-sw/cmssw/pull/45262

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
@cmsbuild abort tests

**Comment by smorovic** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
